#!/bin/bash

#===============================================================================
# Script: obtain-ssl-proxy.sh
# Description: Obtain SSL certificate for app servers (Node.js, Next.js, etc.)
#              Configures Nginx as reverse proxy to a local port
# Usage: sudo ./obtain-ssl-proxy.sh <domain> <port> [email] [--staging]
#
# Examples:
#   sudo ./obtain-ssl-proxy.sh api.example.com 3000 admin@example.com
#   sudo ./obtain-ssl-proxy.sh myapp.com 3000 admin@example.com
#===============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${CYAN}[STEP]${NC} $1"
}

print_usage() {
    echo ""
    echo "Usage: $0 <domain> <port> [email] [--staging]"
    echo ""
    echo "For: App servers (Node.js, Next.js, Express, etc.)"
    echo ""
    echo "Arguments:"
    echo "  domain    - Domain name(s) for the certificate"
    echo "              Single: example.com"
    echo "              Multiple: \"example.com,www.example.com\""
    echo "  port      - Local port where your app is running (e.g., 3000)"
    echo "  email     - Email for Let's Encrypt notifications (optional)"
    echo "  --staging - Use Let's Encrypt staging server (for testing)"
    echo ""
    echo "Examples:"
    echo "  $0 myapp.com 3000 admin@example.com"
    echo "  $0 api.example.com 4000 admin@example.com"
    echo "  $0 \"example.com,www.example.com\" 3000 admin@example.com"
    echo "  $0 example.com 3000 admin@example.com --staging"
    echo ""
}

#-------------------------------------------------------------------------------
# Check if running as root
#-------------------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

#-------------------------------------------------------------------------------
# Validate arguments
#-------------------------------------------------------------------------------
if [[ $# -lt 2 ]]; then
    log_error "Missing required arguments"
    print_usage
    exit 1
fi

DOMAIN="$1"
APP_PORT="$2"
EMAIL="${3:-}"
STAGING=""

# Check for --staging flag
for arg in "$@"; do
    if [[ "$arg" == "--staging" ]]; then
        STAGING="--staging"
        log_warn "Using Let's Encrypt STAGING server (certificates will NOT be trusted)"
    fi
done

# Remove --staging from email if passed as email
if [[ "$EMAIL" == "--staging" ]]; then
    EMAIL=""
fi

#-------------------------------------------------------------------------------
# Validate port
#-------------------------------------------------------------------------------
if ! [[ "$APP_PORT" =~ ^[0-9]+$ ]] || [[ "$APP_PORT" -lt 1 ]] || [[ "$APP_PORT" -gt 65535 ]]; then
    log_error "Invalid port: $APP_PORT (must be 1-65535)"
    exit 1
fi

#-------------------------------------------------------------------------------
# Validate domain format
#-------------------------------------------------------------------------------
PRIMARY_DOMAIN=$(echo "$DOMAIN" | cut -d',' -f1)
if [[ ! "$PRIMARY_DOMAIN" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$ ]]; then
    log_error "Invalid domain format: $PRIMARY_DOMAIN"
    exit 1
fi

NGINX_CONF_NAME=$(echo "$PRIMARY_DOMAIN" | tr '.' '-')

log_info "SSL Certificate for App Server"
echo "  Domain(s): ${DOMAIN}"
echo "  App Port: ${APP_PORT}"
echo "  Email: ${EMAIL:-'(not provided)'}"
echo "  Mode: ${STAGING:-'Production'}"
echo ""

#-------------------------------------------------------------------------------
# Check prerequisites
#-------------------------------------------------------------------------------
if ! command -v certbot &> /dev/null; then
    log_error "Certbot is not installed. Run setup-certbot.sh first."
    exit 1
fi

if ! command -v nginx &> /dev/null; then
    log_error "Nginx is not installed."
    exit 1
fi

#-------------------------------------------------------------------------------
# Build server_name directive
#-------------------------------------------------------------------------------
IFS=',' read -ra DOMAIN_ARRAY <<< "$DOMAIN"
SERVER_NAMES=""
for d in "${DOMAIN_ARRAY[@]}"; do
    d=$(echo "$d" | xargs)
    SERVER_NAMES="$SERVER_NAMES $d"
done
SERVER_NAMES=$(echo "$SERVER_NAMES" | xargs)

#-------------------------------------------------------------------------------
# Create Nginx configuration for reverse proxy
#-------------------------------------------------------------------------------
log_step "Creating Nginx reverse proxy configuration..."

cat > /etc/nginx/sites-available/${NGINX_CONF_NAME} << EOF
# Nginx configuration for ${PRIMARY_DOMAIN} (Reverse Proxy)
# Generated by obtain-ssl-proxy.sh on $(date)

upstream ${NGINX_CONF_NAME}_backend {
    server 127.0.0.1:${APP_PORT};
    keepalive 64;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${SERVER_NAMES};

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

    # Request size limit
    client_max_body_size 50M;

    # WebSocket support
    location /ws {
        proxy_pass http://${NGINX_CONF_NAME}_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
    }

    location /socket.io {
        proxy_pass http://${NGINX_CONF_NAME}_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
    }

    # Main proxy
    location / {
        proxy_pass http://${NGINX_CONF_NAME}_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }
}
EOF

#-------------------------------------------------------------------------------
# Enable site
#-------------------------------------------------------------------------------
log_step "Enabling Nginx site..."

rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
ln -sf /etc/nginx/sites-available/${NGINX_CONF_NAME} /etc/nginx/sites-enabled/

nginx -t
systemctl reload nginx

#-------------------------------------------------------------------------------
# Build and run certbot command
#-------------------------------------------------------------------------------
log_step "Obtaining SSL certificate..."

CERTBOT_CMD="certbot --nginx"

for d in "${DOMAIN_ARRAY[@]}"; do
    d=$(echo "$d" | xargs)
    CERTBOT_CMD="$CERTBOT_CMD -d $d"
done

if [[ -n "$EMAIL" ]]; then
    CERTBOT_CMD="$CERTBOT_CMD --email $EMAIL"
else
    CERTBOT_CMD="$CERTBOT_CMD --register-unsafely-without-email"
fi

[[ -n "$STAGING" ]] && CERTBOT_CMD="$CERTBOT_CMD --staging"

CERTBOT_CMD="$CERTBOT_CMD --non-interactive --agree-tos --redirect"

echo "Running: $CERTBOT_CMD"
eval $CERTBOT_CMD

#-------------------------------------------------------------------------------
# Final summary
#-------------------------------------------------------------------------------
echo ""
echo "=============================================="
log_info "SSL Certificate configured successfully!"
echo "=============================================="
echo ""
echo "Type: App Server (Reverse Proxy)"
echo "Domain(s): ${DOMAIN}"
echo "Proxying to: localhost:${APP_PORT}"
echo ""
echo "Your site is now accessible via HTTPS:"
for d in "${DOMAIN_ARRAY[@]}"; do
    d=$(echo "$d" | xargs)
    echo "  - https://${d}"
done
echo ""
echo "Nginx config: /etc/nginx/sites-available/${NGINX_CONF_NAME}"
echo ""
echo "Features configured:"
echo "  ✓ HTTP → HTTPS redirect (by Certbot)"
echo "  ✓ Reverse proxy to localhost:${APP_PORT}"
echo "  ✓ WebSocket support (/ws, /socket.io)"
echo "  ✓ Gzip compression"
echo ""
if [[ -n "$STAGING" ]]; then
    log_warn "This is a STAGING certificate - browsers will show security warnings!"
fi
echo ""


